<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Ashutoshs-Air" failures="0" tests="1" name="myTest.ExpectedExceptionConcept" time="0.007" errors="1" timestamp="07 Apr 2022 18:24:47 GMT" skipped="0">
  <testcase classname="myTest.ExpectedExceptionConcept" name="loginTest" time="0.007">
    <error message="
Method ExpectedExceptionConcept.loginTest()[pri:0, instance:myTest.ExpectedExceptionConcept@2b4bac49] should have thrown an exception of any of types [class java.lang.ArithmeticException, class java.lang.NullPointerException]" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Method ExpectedExceptionConcept.loginTest()[pri:0, instance:myTest.ExpectedExceptionConcept@2b4bac49] should have thrown an exception of any of types [class java.lang.ArithmeticException, class java.lang.NullPointerException]
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:80)
at org.testng.internal.Invoker.considerExceptions(Invoker.java:1140)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:615)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- loginTest -->
</testsuite> <!-- myTest.ExpectedExceptionConcept -->
